### PR TITLE
Technical debt instalment 2 :grin:

### LINKED ISSUE #9: Treating `UnexpectedEof` as end-of-iteration can silently ignore truncated/corrupt files
Treating `UnexpectedEof` as end-of-iteration can silently ignore truncated/corrupt files (e.g., 1–3 bytes of a length prefix at the end). Consider distinguishing “clean EOF” vs “partial read” by using `Read::read` first and only returning `None` on `Ok(0)`, otherwise error if fewer than 4 bytes are available for the length prefix.
```suggestion
        let mut bytes_read = 0;
        while bytes_read < len_buf.len() {
            match self.reader.reader.read(&mut len_buf[bytes_read..]) {
                Ok(0) => {
                    if bytes_read == 0 {
                        // Clean EOF: no more records.
                        return None;
                    } else {
                        // Partial read of the length prefix: treat as an error.
                        let err = std::io::Error::new(
                            std::io::ErrorKind::UnexpectedEof,
                            "truncated length prefix",
                        );
                        return Some(Err(err.into()));
                    }
                }
                Ok(n) => {
                    bytes_read += n;
                }
                Err(ref e) if e.kind() == std::io::ErrorKind::Interrupted => {
                    // Retry on interrupt.
                    continue;
                }
                Err(e) => {
                    return Some(Err(e.into()));
                }
            }
```

_Originally posted by @Copilot in https://github.com/tweag/cardano-scrawls/pull/6#discussion_r2790421942_

### PR DESCRIPTION
**Pull request by Xophmeister**
Depends on #25

- Detect truncated records during read (resolves #9)
- Compute manifest offset, rather than exposing it as a public field

### CODE REVIEW

File: src/records/manifest.rs [hunk 1]
```diff
@@ -76,21 +57,167 @@ impl Manifest {
...
+        // Length prefixed (u32) UTF-8 strings
+        let created_at_len = 4 + self.summary.created_at.len();
+        let tool_len = 4 + self.summary.tool.len();
+        let comment_len = 4 + self.summary.comment.as_ref().map_or(0, String::len);
+
+        let ns_info_len = self.namespace_info.iter().fold(0usize, |acc, ns_info| {
+            // Namespace info wire length:
+            // len_ns(4) + entries(8) + chunks(8) + namespace(len_ns) + digest(HASH_SIZE)
+            acc + 4 + 8 + 8 + ns_info.name.len() + HASH_SIZE
+        });
```
[the remark this answers is not in the document]
Comment (Xophmeister) [reply src/records/manifest.rs]: Technically this is true...but I think if people are entering 16EiB of tool/comment strings, then you've probably got bigger things to worry about.

File: src/records/manifest.rs [hunk 2]
```diff
@@ -76,21 +57,167 @@ impl Manifest {
 
         buf.write_all(&self.prev_manifest.to_be_bytes())?;
         buf.write_all(self.root_hash.as_bytes())?;
-        buf.write_all(&self.offset.to_be_bytes())?;
+        buf.write_all(&len.to_be_bytes())?;
 
         // Record length should equal offset
-        if buf.len() != self.offset as usize {
+        if buf.len() != self.offset()? as usize {
```
Comment (joaosreis) [inline src/records/manifest.rs]:
```suggestion
        if buf.len() != len as usize {
```

**Review by joaosreis — APPROVED** [review]
LGTM. Just left one nitpick suggestion

File: src/records/manifest.rs (hunk 2 above)
Comment (Xophmeister) [reply src/records/manifest.rs]: Good point! No need to compute it twice :see_no_evil:
